server:
  port: 8080
  servlet:
    context-path: /driving-school-management
spring:
  application:
    name: M_BL5_G4_SU25
  datasource:
    url: jdbc:mysql://localhost:3306/driving_school_management
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

outbound:
  identity:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "n6o81j7T49u61O2h2c7P1y3p0r1I9w8L2k5R8s3T4o2X3j5V9m7Q0e4A8b6C9d5H4v0F1z7E"
  valid-duration: 36000 #in seconds
  refreshable-duration: 36000 #in seconds

